import Head from 'next/head';
import DarkMode from './darkMode';
import styles from '../styles/Home.module.css'
import Image from 'next/image';
import { useState } from 'react';

export default function Layout(props: any) {
  let [mode, setMode] = useState("");

  return (
    <div className={`${mode} min-h-screen flex flex-col`}>
      <div className="bg-neutral-200 dark:bg-slate-800 h-full">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>      
          <div className="bg-gray-400 dark:bg-slate-900 pt-2 relative items-center text-center h-8">
            <span className="dark:text-white text-black">Book Api</span>
            <DarkMode className="absolute top-0 right-0 mt-2 mr-2" setMode={setMode} mode={mode} />
          </div>
          
          <div className="grow min-h-screen my-0 mx-auto w-5/6 dark:text-white text-black">
            <div className="mt-28">
              {props.children}
            </div>
          </div>

        </div>
      </div>
  );
}
